openapi: 3.0.0
info:
  title: ACME Box of the month
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/subscription/{id}':
    post:
      summary: ''
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subscription:
                  type: object
                  required:
                    - customer_attributes
                    - credit_card_attributes
                  properties:
                    customer_attributes:
                      type: object
                      required:
                        - first_name
                        - last_name
                        - adress
                        - zip_code
                      properties:
                        first_name:
                          type: string
                        last_name:
                          type: string
                        adress:
                          type: string
                        zip_code:
                          type: string
                    credit_card_attributes:
                      type: object
                      required:
                        - card_number
                        - card_type
                        - expiration_month
                        - expiration_year
                        - cvv
                        - card_holder_name
                        - zip_code
                      properties:
                        card_number:
                          type: string
                        card_type:
                          type: string
                        expiration_month:
                          type: number
                        expiration_year:
                          type: number
                        cvv:
                          type: number
                        card_holder_name:
                          type: string
                        zip_code:
                          type: string
              required:
                - subscription
      description: "When a request to API endpoint is made, you will attempt a \"purchase\" with the customer's payment information. If the purchase is successful, a new subscription will be created."
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Subscription ID
  /auth:
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    $ref: ../common/models/user.v1.yaml
              examples:
                example:
                  value:
                    status: success
                    data:
                      uid: karol@krl.im
                      id: 1
                      email: karol@krl.im
                      provider: email
                      allow_password_change: false
                      name: null
                      nickname: null
                      image: null
                      created_at: '2019-09-23T11:42:37.438Z'
                      updated_at: '2019-09-23T11:42:37.584Z'
          headers:
            access_token:
              schema:
                type: string
              description: |
                Api Access Token
              required: true
            uid:
              schema:
                type: string
              description: User uid
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
              examples:
                example:
                  value:
                    success: false
                    errors:
                      - Please submit proper sign up data in request body.
                    status: error
      description: Email registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                name:
                  type: string
                nickname:
                  type: string
                image:
                  type: string
              required:
                - email
                - password
                - password_confirmation
  /auth/sign_in:
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ../common/models/user.v1.yaml
          headers:
            access_token:
              schema:
                type: string
              description: User access token
      description: User Sign In
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
        description: ''
components:
  schemas: {}
  securitySchemes:
    'API Key ':
      name: API Key
      type: apiKey
      in: header
